# Generated by Django 4.2.5 on 2023-09-13 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_personalmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personalmessage",
            options={"ordering": ("timestamp",)},
        ),
    ]
